In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# number of dimensions
a.ndim, b.ndim

(1, 2)

In [15]:
# get shape
b.shape

(2, 3)

In [16]:
# get type
a.dtype

dtype('int64')

In [21]:
# get size per item
a.itemsize

8

In [17]:
b.dtype

dtype('float64')

In [18]:
c = np.array([1,2,4], dtype='int8')
print(c)

[1 2 4]


In [19]:
c.dtype

dtype('int8')

In [20]:
c.itemsize

1

In [24]:
# get total size
c.size * c.itemsize

3

In [25]:
b.size * b.itemsize

48

In [26]:
b.nbytes

48

In [27]:
# accessing changing elements
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
d.shape

(2, 7)

In [31]:
# get specific element [row, col]
d[1, 5]

13

In [32]:
d[1, -2]

13

In [33]:
# get a specific row
d[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
d[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
# get specific columns
d[:, 2]

array([ 3, 10])

In [37]:
# get more specific  [startindex, endindex, stepsize]
# get every other elements between 2 and 6
d[0, 1:6:2]

array([2, 4, 6])

In [38]:
# to change 13
d[1,5] = 20
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
# to chaneg a column
d[:, 1] = 99
print(d)

[[ 1 99  3  4  5  6  7]
 [ 8 99 10 11 12 20 14]]


In [40]:
d[:, 2] = [33, 111]
print(d)

[[  1  99  33   4   5   6   7]
 [  8  99 111  11  12  20  14]]


In [41]:
# 3d example
e = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(e)
              

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
e.ndim

3

In [43]:
e.shape

(2, 2, 2)

In [44]:
# to get specific item work outside in 
# to get 4
e[0, 1, 1]

4

In [45]:
# to get [7,8]
e[1,1, :]

array([7, 8])

In [46]:
# replace e[:, 1, :]  second row on each plane
e[:, 1, :] = [[9,9], [0,0]]
print(e)

[[[1 2]
  [9 9]]

 [[5 6]
  [0 0]]]


In [47]:
# all zeros 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
# all ones
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [55]:
# to initialize to any number  np.full(shape, value, dtype)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [58]:
np.full(a.shape, 4)

array([4, 4, 4])

In [59]:
np.full_like(a, 8)

array([8, 8, 8])

In [60]:
# random decimal  4x2
np.random.rand(4,2)

array([[0.66136411, 0.01275828],
       [0.24793589, 0.18959667],
       [0.79506998, 0.0130893 ],
       [0.79784635, 0.88104617]])

In [61]:
np.random.random_sample(b.shape)

array([[0.12023086, 0.31343431, 0.43313575],
       [0.70863346, 0.67756628, 0.89522903]])

In [65]:
# random integer values start, end, shape(size)
np.random.randint(2,7, size=(3,3))

array([[3, 4, 6],
       [6, 5, 3],
       [2, 2, 2]])

In [67]:
# identity matrix (RxR)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
# repeat array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [77]:
# generate this array
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1 
ar1 = np.ones((5,5), dtype='int8')
ar1[1:-1, 1:-1] = 0
ar1[2,2] = 9
print(ar1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Copies are pointer referencce

In [78]:
x = np.array([1,2,3])
y=x
print(y)

[1 2 3]


In [79]:
y[0] = 100
print(x)

[100   2   3]


In [80]:
x = np.array([1,2,3])

In [81]:
z=x.copy()
z[0]=100
print(x)
print(z)

[1 2 3]
[100   2   3]


### Numpy provides elementwise arithmatic

In [95]:
aa = np.array([1,2,3])
print(aa)

[1 2 3]


In [83]:
aa+2

array([3, 4, 5])

In [84]:
aa - 2

array([-1,  0,  1])

In [85]:
aa * 2

array([2, 4, 6])

In [86]:
aa / 2

array([0.5, 1. , 1.5])

In [91]:
aa += 2

In [92]:
print(aa)

[5 6 7]


In [96]:
# used original aa here
bb = np.array([1,0,1])
aa+bb

array([2, 2, 4])

In [98]:
a**2

array([1, 4, 9])

In [99]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [100]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

### Checkout https://docs.scipy.org/doc/numpy/reference/routines.math.html

# Linear Algebra

In [104]:
m1 = np.ones((2,3))
print(m1)

m2= np.full((3,2), 2)
print(m2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [106]:
# matrix multiplication of m1(2,3) x m2(3,2) = out(2x2)
# m1 x m2 doesn't work
np.matmul(m1, m2)


array([[6., 6.],
       [6., 6.]])

In [108]:
# find the determinate
m3 = np.identity(3)
np.linalg.det(m3)

1.0

### Checkout https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

# Statistics

In [110]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.min(stats)

1

In [112]:
np.max(stats)

6

In [115]:
# axices are row 0, col 1
x1 = np.min(stats, axis=0)
print(x1)
x2 = np.min(stats, axis=1)
print(x2)

[1 2 3]
[1 4]


In [116]:
np.sum(stats)

21

In [117]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [118]:
np.sum(stats, axis=1)

array([ 6, 15])

### reorganizing arrays

In [120]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [121]:
before.shape

(2, 4)

In [129]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [130]:
aftert = before.reshape((4,2))
print(aftert)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [132]:
# vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [133]:
# horizontal stack
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscelleneous

In [139]:
filedata =np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.],
       [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
        120., 130., 140., 150., 160., 170., 180.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
         60.,  65.,  70.,  75.,  80.,  85.,  90.]])

In [140]:
filedata.astype('int32')

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90]], dtype=int32)

## Boolean masking and advanced indexing

In [141]:
filedata > 50.

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True]])

In [143]:
filedata >= 20

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [144]:
filedata[filedata > 50]

array([ 60.,  70.,  80.,  90., 100., 110., 120., 130., 140., 150., 160.,
       170., 180.,  55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.])

#### Use list as index

In [145]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1[[0,2, 5, 7]]

array([1, 3, 6, 8])

In [146]:
# looking downwards on columns if any
np.any(filedata > 50, axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [147]:
# looking to the right on rows if any
np.any(filedata > 50, axis=1)

array([False,  True,  True])

In [149]:
# looking downwards on columns if all
np.all(filedata > 5, axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [151]:
# looking to the right on rows if all
np.all(filedata >= 5, axis=1)

array([False,  True,  True])

In [152]:
((filedata > 5) & (filedata < 30))

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [154]:
# not
(~((filedata > 5) & (filedata < 30)))

array([[ True,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [158]:
mtrx1 = np.genfromtxt('matrix2.txt', delimiter=',').astype('int8')
print(mtrx1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [159]:
q1 = mtrx1[2:4,0:2]
print(q1)

[[11 12]
 [16 17]]


In [166]:
q2=mtrx1.reshape(30)[1:21:6]
q2

array([ 2,  8, 14, 20], dtype=int8)

In [165]:
# or
mtrx1[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20], dtype=int8)

In [198]:
mtrx1[[0,4,5], 3:]


array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int8)